FROM node:latest AS base

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY src ./src
COPY tsconfig.json ./tsconfig.json

RUN npm run build


FROM node:latest

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true
ENV PUPPETEER_SKIP_DOWNLOAD true

# Install Google Chrome Stable and fonts
# Note: this installs the necessary libs to make the browser work with Puppeteer.
RUN apt-get update && apt-get install gnupg wget -y && \
    wget --quiet --output-document=- https://dl-ssl.google.com/linux/linux_signing_key.pub | gpg --dearmor > /etc/apt/trusted.gpg.d/google-archive.gpg && \
    sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' && \
    apt-get update && \
    apt-get install google-chrome-stable -y --no-install-recommends && \
    rm -rf /var/lib/apt/lists/*


RUN npm install pm2 -g

WORKDIR /app

COPY package* ./
RUN npm install --production

COPY --from=base ./app/node_modules ./node_modules
COPY --from=base ./app/build ./build

ENV MONGO_URL=mongodb://mongo:27017/BA
ENV API_KEY=XXX
ENV TZ=Europe/Amsterdam
ENV NODE_ENV=production
ENV SEARCH_API_KEY=XXX

EXPOSE 8000

CMD ["pm2-runtime", "build/server.js"]

